// full-stack-app/react-client-app/src/components/CarForm.js
import styled from 'styled-components';

import { useForm } from '../hooks/useForm';

const Label = styled.label`
  display: block;
`;

export const CarForm = ({ buttonText, onSubmitCar }) => {

  const [ carForm, change, resetCarForm ] = useForm({
    make: '', model: '', year: 1900, color: '', price: 0,
  });

  const submitCar = () => {
    onSubmitCar({...carForm });
    resetCarForm();
  };

  return (
    <form className="carForm">
      <Label>
        Make:
        <input type="text" name="make" value={carForm.make} onChange={change} />
      </Label>
      <Label>
        Model:
        <input type="text" name="model" value={carForm.model} onChange={change} />
      </Label>
      <Label>
        Year:
        <input type="number" name="year" value={carForm.year} onChange={change} />
      </Label>
      <Label>
        Color:
        <input type="text" name="color" value={carForm.color} onChange={change} />
      </Label>
      <Label>
        Price:
        <input type="number" name="price" value={carForm.price} onChange={change} />
      </Label>
      <button type="button" onClick={submitCar}>{buttonText}</button>
    </form>
  );

};

CarForm.defaultProps = {
  buttonText: "Submit Car",
};

// full-stack-app/angular-client-app/src/app/car-tool/components/car-form/car-form.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { NewCar } from '../../models/cars';

@Component({
  selector: 'app-car-form',
  templateUrl: './car-form.component.html',
  styleUrls: ['./car-form.component.css']
})
export class CarFormComponent implements OnInit {

  @Input()
  buttonText = "Submit Car";

  carForm!: FormGroup;

  @Output()
  submitCar = new EventEmitter<NewCar>();

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.carForm = this.fb.group({
      make: '',
      model: '',
      year: 1900,
      color: '',
      price: 0,
    });
  }

  doSubmitCar() {
    console.log(this.carForm.value);
    this.submitCar.emit(this.carForm.value);
  }

}

<form [formGroup]="carForm">
  <label>
    Make:
    <input type="text" formControlName="make">
  </label>
  <label>
    Model:
    <input type="text" formControlName="model">
  </label>
  <label>
    Year:
    <input type="number" formControlName="year">
  </label>
  <label>
    Color:
    <input type="text" formControlName="color">
  </label>
  <label>
    Price:
    <input type="number" formControlName="price">
  </label>
  <button type="button" (click)="doSubmitCar()">
    {{buttonText}}
  </button>
</form>
