// full-stack-app/react-client-app/src/components/ColorForm.js
import styled from 'styled-components';

import { useForm } from '../hooks/useForm';

const Label = styled.label`
  display: block;
`;

export const ColorForm = ({ buttonText, onSubmitColor }) => {

  const [ colorForm, change, resetColorForm ] = useForm({
    name: '', hexcode: '',
  });

  const submitColor = () => {
    onSubmitColor({...colorForm });
    resetColorForm();
  };

  return (
    <form className="colorForm">
      <Label>
        Name:
        <input type="text" name="name" value={colorForm.name} onChange={change} />
      </Label>
      <Label>
        Hexcode:
        <input type="text" name="hexcode" value={colorForm.hexcode} onChange={change} />
      </Label>
      <button type="button" onClick={submitColor}>{buttonText}</button>
    </form>
  );

};

ColorForm.defaultProps = {
  buttonText: "Submit Color",
};

// full-stack-app/angular-client-app/src/app/color-tool/components/color-form/color-form.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { NewColor } from '../../models/colors';

@Component({
  selector: 'app-color-form',
  templateUrl: './color-form.component.html',
  styleUrls: ['./color-form.component.css']
})
export class ColorFormComponent implements OnInit {

  @Input()
  buttonText = "Submit Color";

  colorForm!: FormGroup;

  // private fb: FormBuilder;

  // constructor(fb: FormBuilder) {
  //   this.fb = fb;
  // }

  @Output()
  submitColor = new EventEmitter<NewColor>();

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.colorForm = this.fb.group({
      name: '',
      hexcode: '',
    });
  }

  doSubmitColor() {
    this.submitColor.emit(this.colorForm.value);
  }

}

<form [formGroup]="colorForm">
  <label>
    Name:
    <input type="text" formControlName="name" />
  </label>
  <label>
    Hexcode:
    <input type="text" formControlName="hexcode" />
  </label>
  <button type="button" (click)="doSubmitColor()">
    {{buttonText}}</button>
</form>
