// react-demo-app/src/components/CarForm.js
import { useState } from "react";
import styled from 'styled-components';


const Label = styled.label`
  display: block;
`;

export const CarForm = (props) => {

  const [carForm, setCarForm] = useState({
    make: '', model: '', year: 1900, color: '', price: 0,
  });

  const change = (evt) => {
    setCarForm({
      ...carForm,
      [evt.target.name]:evt.target.type === 'number'
        ? evt.target.valueAsNumber : evt.target.value,
    });
  };

  const submitCar = () => {
    props.onSubmitCar({ ...carForm });
  };

  return (
    <form>
      <Label>
        Make:
        <input type="text" name="make"
          value={carForm.make} onChange={change} />
      </Label>
      <Label>
        Model:
        <input type="text" name="model"
          value={carForm.model} onChange={change} />
      </Label>
      <Label>
        Year:
        <input type="number" name="year"
          value={carForm.year} onChange={change} />
      </Label>
      <Label>
        Color:
        <input type="text" name="color"
          value={carForm.color} onChange={change} />
      </Label>
      <Label>
        Price:
        <input type="number" name="price"
          value={carForm.price} onChange={change} />
      </Label>
      <button type="button" onClick={submitCar}>Add Car</button>
    </form>
  );

};

// angular-demo-app/src/app/car-tool/components/car-form/car-form.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

import { NewCar } from '../../models/cars';

@Component({
  selector: 'app-car-form',
  templateUrl: './car-form.component.html',
  styleUrls: ['./car-form.component.css']
})
export class CarFormComponent implements OnInit {

  carForm!: FormGroup;

  @Output()
  submitCar = new EventEmitter<NewCar>();

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {

    this.carForm = this.fb.group({
      make: '', model: '', year: 1900, color: '', price: 0,
    });

  }

  doSubmitCar() {
    this.submitCar.emit(this.carForm.value);
  }

}

<form [formGroup]="carForm">
  <label>
    Make:
    <input type="text" formControlName="make">
  </label>
  <label>
    Model:
    <input type="text" formControlName="model">
  </label>
  <label>
    Year:
    <input type="number" formControlName="year">
  </label>
  <label>
    Color:
    <input type="text" formControlName="color">
  </label>
  <label>
    Price:
    <input type="number" formControlName="price">
  </label>
  <button (click)="doSubmitCar()">Add Car</button>
</form>
