// angular-demo-app/src/app/color-tool/components/color-form/color-form.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

import { NewColor } from '../../models/colors';

@Component({
  selector: 'app-color-form',
  templateUrl: './color-form.component.html',
  styleUrls: ['./color-form.component.css']
})
export class ColorFormComponent implements OnInit {

  colorForm!: FormGroup;

  @Output()
  submitColor = new EventEmitter<NewColor>();

  // private fb: FormBuilder;

  // constructor(fb: FormBuilder) {
  //   this.fb = fb;
  // }

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {

    this.colorForm = this.fb.group({
      name: '',
      hexcode:'',
    });

  }

  doSubmitColor() {
    this.submitColor.emit(this.colorForm.value);
  }

}

<form [formGroup]="colorForm">
  <label>
    Name:
    <input type="text" formControlName="name">
  </label>
  <label>
    Hexcode:
    <input type="text" formControlName="hexcode">
  </label>
  <button (click)="doSubmitColor()">Add Color</button>
</form>

// react-demo-app/src/components/ColorForm.js
import { useState } from "react";

export const ColorForm = (props) => {

  const [ colorForm, setColorForm ] = useState({
    name: '', hexcode: '',
  });

  const change = (evt) => {
    setColorForm({
      ...colorForm,
      [ evt.target.name ]: evt.target.value,
    });
  };

  const submitColor = () => {
    props.onSubmitColor({ ...colorForm });
  };

  return (
    <form>
      <label>
        Name:
        <input type="text" name="name" value={colorForm.name} onChange={change} />
      </label>
      <label>
        Hexcode:
        <input type="text" name="hexcode" value={colorForm.hexcode} onChange={change} />
      </label>
      <button type="button" onClick={submitColor}>Add Color</button>
    </form>
  );

};
